initial models commit
cssgunc/compass pull request #22
Opened 2024-03-25 23:09 UTC by manyuagashe

2024-03-25 23:35 UTC, aidankim12 approved these changes
Worked together with Manyu as he created the file.

2024-03-25 23:51 UTC, bhardee16 requested changes

2024-03-25 23:51 UTC, bhardee16 commented on backend/models/service_model.py
> +    summary: str
This is good, but I think for consistency sake, we should either stick with defining as `str` or `Field(..., max_length=150, description="The name of the service")`. Similar to how Resource was defined.

2024-03-25 23:51 UTC, bhardee16 commented on backend/models/tag_model.py
> +    created_at: datetime | None = None
For consistency: either `created_at: Optional[datetime]` or `created_at: datetime | None = None`.

2024-03-25 23:51 UTC, bhardee16 commented on backend/models/service_model.py
> +    created_at: datetime | None = None
For consistency: either created_at: Optional[datetime] or created_at: datetime | None = None.

2024-03-25 23:51 UTC, bhardee16 commented on backend/models/resource_model.py
> +    created_at: Optional[datetime]
For consistency: either created_at: Optional[datetime] or created_at: datetime | None = None.

2024-03-25 23:51 UTC, bhardee16 commented on backend/models/user_model.py
> +    created_at: Optional[datetime]
For consistency: either created_at: Optional[datetime] or created_at: datetime | None = None.

2024-03-26 00:11 UTC, bhardee16 approved these changes

2024-03-26 00:13 UTC, merged